### ISSUE TITLE
unexpected response from server [500]: Too many open files

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/Darjeeling#130]
On a single program that I'm running algorithm type genetic, I'm seeing the following exception occur a few times:
```
<title>requests.exceptions.ConnectionError: ('Connection aborted.', OSError(24, 'Too many open files')) // Werkzeug Debugger</title>
```
I captured the STDOUT to a debug.log, so if this is something that is of interest to debug, I can attach that log.

errata: I have a large population size and number of generations that probably contributes to the expression of this error: 
```
algorithm:
  type: genetic
  population: 200
  generations: 200
  tournament-size: 20
  mutation-rate: 0.8
  crossover-rate: 0.4
  # look at entire test suite for test sampling [subset of testsuite is 100%]
  test-sample-size: null
```

Looks like this ConnectionError ultimately results in the darjeeling process to hang. I'm guessing that it's waiting for evaluation data from the lost Candidates.

---

submitted from [GitQ](https://gitq.com/squaresLab/Darjeeling/topics/11/unexpected-response-from-server-500-too-many-open-files/1)
