### ISSUE TITLE
Does 'seed' ensure that the same children/mutations are generated for a yml configuration and program [using algorithm type genetic]?

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/Darjeeling#135]
I was able to duplicate the scenario where not only do I see different candidates from the STDOUT Darjeeling repair, but also some different repairs.
I launched a few back to back darjeeling runs like so with the :
```
for i in $(seq 0 1 10); do 
    mkdir -p seed.test.$i; 
    cd seed.test.$i; 
    darjeeling repair --seed 12345678 ../../no_seed.yml |& tee darjeeling.repair.log.seed_12345678; 
    cd ../; 
done
```
Please note that I'm using the genetic algorithm:
```
algorithm:
  type: genetic
  population: 200
  generations: 200
  tournament-size: 20
  mutation-rate: 0.8
  crossover-rate: 0.4
  # look at entire test suite for test sampling [subset of testsuite is 100%]
  test-sample-size: null
```
and I'm not only seeing different candidates, but some different repairs.  I have a tarball of the logs and outputs, will upload.

---

submitted from [GitQ](https://gitq.com/squaresLab/Darjeeling/topics/12/does-seed-ensure-that-the-same-children-mutations-are-generated-for-a-yml-configuration-and-program/5)
