### ISSUE TITLE
Add ability to specify bugs/problems via Docker rather than BugZoo

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/Darjeeling#228]
```
problem:
  type: docker
  language: c++
  image: hello-world
coverage:
  instrumentation:
    type: gcov | sancov | jcov | cobertura | jacoco
```

The problem description would need the following components:
* the location of the source code files within the container
* instructions for building the program
* instructions for instrumenting the program for coverage
